import { createHash, createHmac, randomBytes } from "node:crypto";

/**
 * Provably-fair primitives for the Fortune Wheel.
 *
 * A spin's outcome is derived deterministically from three inputs:
 *   - serverSeed  — secret, generated by the server; its SHA-256 hash is stored
 *                   on the wager row and revealed (alongside the seed) after the
 *                   spin so the player can confirm it was not chosen post-hoc.
 *   - clientSeed  — optionally supplied by the player.
 *   - nonce       — the player's prior wager count, making every spin unique.
 *
 * roll = first 32 bits of HMAC-SHA256(serverSeed, "<clientSeed>:<nonce>"),
 * normalised to [0, 1). Anyone can recompute it from the revealed values.
 */

/** Bytes of entropy in a generated server seed. */
const SERVER_SEED_BYTES = 32;

/** 2^32 — divisor that maps a 32-bit integer into [0, 1). */
const UINT32_RANGE = 0x1_0000_0000;

/** Generate a fresh random server seed as a hex string. */
export function generateServerSeed(): string {
	return randomBytes(SERVER_SEED_BYTES).toString("hex");
}

/** SHA-256 hex digest of a seed — the value committed before a spin resolves. */
export function hashSeed(seed: string): string {
	return createHash("sha256").update(seed).digest("hex");
}

/**
 * Deterministically map (serverSeed, clientSeed, nonce) to a roll in [0, 1).
 * Uses the top 32 bits of the HMAC so the result is stable across platforms.
 */
export function computeRoll(
	serverSeed: string,
	clientSeed: string,
	nonce: number,
): number {
	const digest = createHmac("sha256", serverSeed)
		.update(`${clientSeed}:${nonce}`)
		.digest("hex");
	const slice = parseInt(digest.slice(0, 8), 16);
	return slice / UINT32_RANGE;
}

/**
 * Draw `count` independent rolls for a single multi-roll spin (e.g. the three
 * reels of Shrine Slots). Each roll appends its zero-based index to the HMAC
 * message — `"<clientSeed>:<nonce>:<i>"` — so the reels are independent yet still
 * fully recomputable from the revealed seeds.
 *
 * NOTE the trailing `:<i>` means `computeRolls(...)[0]` is intentionally NOT the
 * same value as {@link computeRoll}; single-roll games keep using `computeRoll`.
 */
export function computeRolls(
	serverSeed: string,
	clientSeed: string,
	nonce: number,
	count: number,
): number[] {
	const rolls: number[] = [];
	for (let index = 0; index < count; index++) {
		const digest = createHmac("sha256", serverSeed)
			.update(`${clientSeed}:${nonce}:${index}`)
			.digest("hex");
		rolls.push(parseInt(digest.slice(0, 8), 16) / UINT32_RANGE);
	}
	return rolls;
}
