SecRule REQUEST_URI "@streq /api/auth/42/callback" \
    "id:100100,phase:1,pass,nolog,ctl:ruleEngine=Off"
SecRule REQUEST_URI "@streq /api/auth/github/callback" \
    "id:100101,phase:1,pass,nolog,ctl:ruleEngine=Off"
