SecRuleEngine On
SecRequestBodyAccess On
SecRequestBodyLimit 10485760
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject
SecResponseBodyAccess Off

SecTmpDir /tmp/modsecurity/tmp
SecDataDir /tmp/modsecurity/data
SecUnicodeMapFile /etc/nginx/modsec/unicode.mapping 20127

SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogFormat JSON
SecAuditLog /var/log/nginx/modsec_audit.log

SecRule REQUEST_HEADERS:Content-Type "application/json" \
    "id:100000,phase:1,pass,nolog,ctl:requestBodyProcessor=JSON"
