import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Creates the chat schema: conversations (dm | group), their membership rows,
 * and messages.
 *
 * Column names are camelCase (quoted) to match the newer-table convention —
 * see wagers, matchReplays, reports — rather than the older snake_case
 * friendships table (see SOCIAL_TAB_HANDOFF.md §9 for that inconsistency).
 *
 * No `notifications` row is created per message — unread state is derived
 * from `conversations."lastMessageAt"` vs.
 * `conversation_participants."lastReadAt"` (see ChatService / Batch 4).
 */
export class CreateChat20260704000000 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS conversations (
        id                    SERIAL       PRIMARY KEY,
        type                  VARCHAR(8)   NOT NULL,
        name                  VARCHAR(255) DEFAULT NULL,
        "ownerId"             INTEGER      REFERENCES users(id) ON DELETE SET NULL,
        "lastMessageAt"       TIMESTAMPTZ  DEFAULT NULL,
        "lastMessagePreview"  TEXT         DEFAULT NULL,
        "createdAt"           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt"           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);

		await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS conversation_participants (
        id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "conversationId"  INTEGER      NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        "userId"          INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        "joinedAt"        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "lastReadAt"      TIMESTAMPTZ  DEFAULT NULL,
        CONSTRAINT uq_conversation_participant UNIQUE ("conversationId", "userId")
      )
    `);

		await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_conversation_participants_userId"
        ON conversation_participants ("userId")
    `);

		await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS messages (
        id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "conversationId"  INTEGER      NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        "senderId"        INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        type              VARCHAR(16)  NOT NULL DEFAULT 'text',
        body              TEXT         NOT NULL,
        metadata          JSONB        DEFAULT NULL,
        "createdAt"       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);

		await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_messages_conversationId_createdAt"
        ON messages ("conversationId", "createdAt")
    `);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP INDEX IF EXISTS "IDX_messages_conversationId_createdAt"`);
		await queryRunner.query(`DROP TABLE IF EXISTS messages`);
		await queryRunner.query(`DROP INDEX IF EXISTS "IDX_conversation_participants_userId"`);
		await queryRunner.query(`DROP TABLE IF EXISTS conversation_participants`);
		await queryRunner.query(`DROP TABLE IF EXISTS conversations`);
	}
}
