/**
 * Mirror of backend/src/modules/tournaments/tournaments.contracts.ts — keep
 * in sync; verified by scripts/check-tournament-contracts.sh.
 *
 * This file is a CONSCIOUS copy (SPEC-037): the backend file is the source
 * of truth. It is deliberately import-free so it can never break the
 * frontend build. Edit BOTH files in the same task, then run the check
 * script.
 *
 * Rules (SPEC-004 / SPEC-022):
 * - No `any`, no generic dictionaries for payloads.
 * - The snapshot is the ONLY source of state (snapshot-first, SPEC-022).
 *   Incremental `tournament:*` events are presentation hints only.
 */

/** Mirror of the entity union (backend: entities/tournament.entity.ts). */
export type TournamentStatus = "pending" | "active" | "finished" | "cancelled";

// ── WS event names (wire events, Socket.IO path /ws/) ─────────────────────────

export const TOURNAMENT_WS_EVENTS = {
	/** Lobby membership / lifecycle changed — carries the full lobby state. */
	LOBBY_UPDATED: "tournament:lobby-updated",
	/** The creator pressed Start; the match lifecycle begins (SPEC-023). */
	STARTING: "tournament:starting",
	/** Authoritative full-state snapshot (snapshot-first sync, SPEC-022). */
	SNAPSHOT: "tournament:snapshot",
} as const;

export type TournamentWsEventName =
	(typeof TOURNAMENT_WS_EVENTS)[keyof typeof TOURNAMENT_WS_EVENTS];

// ── Canonical domain events (SPEC-004 catalog, owner: Entry & Lobby) ──────────

/**
 * Canonical Entry & Lobby event names from the SPEC-004 catalog.
 * Used as the `cause` presentation hint inside `tournament:lobby-updated`.
 * Never a source of state.
 */
export type TournamentLobbyEventName =
	| "TournamentLobbyCreated"
	| "TournamentInviteSent"
	| "TournamentPlayerJoined"
	| "TournamentPlayerLeft"
	| "TournamentLobbyCancelled"
	| "TournamentLobbyCompleted"
	| "TournamentStartRequested";

// ── Client intents (SPEC-022) ──────────────────────────────────────────────────

/**
 * Client intent names — RESERVED for later gameplay phases.
 * Names only (SPEC-022 catalog); payloads are added phase by phase under
 * architect approval. Clients request actions, never send results.
 */
export type TournamentIntentName =
	| "RollDiceIntent"
	| "UseItemIntent"
	| "BuyOfferIntent"
	| "StartGamblingIntent"
	| "LeaveGamblingIntent"
	| "EndTurnIntent";

// ── PIN (architect ruling #2, tournament-platform-seams-audit.md) ─────────────

/** Fixed first character of every tournament PIN. */
export const TOURNAMENT_PIN_PREFIX = "T";
/** Alphabet for the 5 random characters (no ambiguous chars). */
export const TOURNAMENT_PIN_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
/** Total PIN length: prefix + 5 random characters. */
export const TOURNAMENT_PIN_LENGTH = 6;

// ── Shared lobby shapes ────────────────────────────────────────────────────────

/** One seat in the lobby, as exposed to clients. */
export interface TournamentParticipantSummary {
	/** Null if the account was deleted (FK SET NULL). */
	userId: number | null;
	username: string;
	/** Turn-order seat; null while the lobby has not assigned seats yet. */
	seat: number | null;
	/**
	 * Ready-ish flag: true when the participant is connected to the lobby
	 * room. There is no manual ready-check — start is server-initiated
	 * (SPEC-038 / seams-audit ruling #1).
	 */
	ready: boolean;
}

/** Full lobby state — enough to hydrate the entry UI after a refresh. */
export interface TournamentLobbyState {
	id: string;
	status: TournamentStatus;
	/** Shareable join PIN (prefix "T" + 5 chars). */
	pin: string;
	creatorUserId: number;
	participants: TournamentParticipantSummary[];
	/** ISO-8601 timestamps (wire format). */
	createdAt: string;
	/** Lobby expiry deadline (v1: 10 minutes after creation). */
	expiresAt: string;
}

// ── WS payloads ────────────────────────────────────────────────────────────────

/** Payload of `tournament:lobby-updated`. */
export interface TournamentLobbyUpdatedPayload {
	lobby: TournamentLobbyState;
	/** Presentation hint: which canonical event caused this update. */
	cause: TournamentLobbyEventName;
}

/** Payload of `tournament:starting`. */
export interface TournamentStartingPayload {
	tournamentId: string;
	/**
	 * First-round turn order (userIds in play order), generated by the
	 * Runtime from the tournament seed — shown before start (SPEC-038,
	 * subject requirement: visible play order).
	 */
	turnOrder: number[];
}

/**
 * Versioned gameplay snapshot — PLACEHOLDER (version 0).
 * Gameplay fields (board, wallets, inventories, progress, …) are added in
 * later phases under architect approval. Do NOT invent fields here.
 */
export interface TournamentSnapshotV0 {
	version: 0;
	tournamentId: string;
	status: TournamentStatus;
	participants: TournamentParticipantSummary[];
}

/**
 * Payload of `tournament:snapshot` (snapshot-first, SPEC-022).
 * `seq` is monotonic: clients discard any snapshot with seq <= current.
 */
export interface TournamentSnapshotEnvelope {
	seq: number;
	snapshot: TournamentSnapshotV0;
}

// ── REST request shapes (implemented by tournaments.dto.ts classes) ───────────

/** Body of POST /tournaments/:id/invite. */
export interface InviteTournamentRequest {
	/** Friend to invite (must be a friend, never a guest). */
	userId: number;
}

/** Body of POST /tournaments/join-pin. */
export interface JoinTournamentByPinRequest {
	/** Case-insensitive; normalized to uppercase server-side. */
	pin: string;
}

// ── REST response shapes ───────────────────────────────────────────────────────

/** POST /tournaments — lobby created in `pending`. */
export type CreateTournamentResponse = TournamentLobbyState;
/**
 * GET /tournaments/:id — lobby/game state for UI hydration.
 * Active-game hydration (snapshot) is added in later phases.
 */
export type GetTournamentResponse = TournamentLobbyState;
/** POST /tournaments/:id/invite — lobby state after the invite is sent. */
export type InviteTournamentResponse = TournamentLobbyState;
/** POST /tournaments/:id/join — lobby state after accepting the invite. */
export type JoinTournamentResponse = TournamentLobbyState;
/** POST /tournaments/join-pin — lobby state after joining by PIN. */
export type JoinTournamentByPinResponse = TournamentLobbyState;
/** POST /tournaments/:id/leave — status is `cancelled` if the creator left. */
export type LeaveTournamentResponse = TournamentLobbyState;
/** POST /tournaments/:id/start — creator only; status becomes `active`. */
export type StartTournamentResponse = TournamentLobbyState;
